version: "1"
services:
  ui-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - hrsApp

networks:
  hrsApp:
    name: "hrsApp"
    driver: bridge
