version: "1"
services:
  ui-app:
    container_name: ui-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - hrsApp

networks:
  hrsApp:
    name: "hrsApp"
    driver: bridge
