version: "1"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: Taomatkhau1
    ports:
      - "9200:9200"
    networks:
      - hrsApp
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.3
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - hrsApp
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - hrsApp
    depends_on:
      - elasticsearch
    restart: always

networks:
  hrsApp:
    name: "hrsApp"
    driver: bridge
