const { Reservation } = require("../models/Reservation");
const { Room } = require("../models/Room");
const { SelfStudyArea } = require("../models/SelfStudyArea");
const { v4: uuidv4 } = require("uuid");

const ssaId = {
  H1: "78ef2a22-8efa-4efe-9ae5-5f6050a1bec2",
  H2: "8e805229-9cb2-463e-a8a2-01eb077af1a2",
  H3: "f9069cbe-0987-42f1-91ef-3a391180ffaa",
  H6: "39607138-11b3-4be5-8cea-5ca5509df11d",
  B4: "e7b42d25-03db-4139-91b5-d9e03eaf4abb",
  A4: "2c94b72c-c7a2-46e5-952a-f051c3acc215",
};

async function seed() {
  await SelfStudyArea.bulkCreate([
    {
      id: ssaId.H1,
      building: "H1",
    },
    {
      id: ssaId.H2,
      building: "H2",
    },
    {
      id: ssaId.H3,
      building: "H3",
    },
    {
      id: ssaId.H6,
      building: "H6",
    },
    {
      id: ssaId.B4,
      building: "B4",
    },
    {
      id: ssaId.A4,
      building: "A4",
    },
  ]);

  await Room.bulkCreate([
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-101",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-102",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-103",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-201",
      capacity: 5,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-202",
      capacity: 6,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-203",
      capacity: 7,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-301",
      capacity: 10,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-302",
      capacity: 15,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H1,
      name: "H1-303",
      capacity: 20,
      type: "Mentoring",
      floor: "3",
    },

    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-101",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-102",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-103",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-201",
      capacity: 5,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-202",
      capacity: 6,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-203",
      capacity: 7,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-301",
      capacity: 10,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-302",
      capacity: 15,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H2,
      name: "H2-303",
      capacity: 20,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-101",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-102",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-103",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-201",
      capacity: 5,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-202",
      capacity: 6,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-203",
      capacity: 7,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-301",
      capacity: 10,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-302",
      capacity: 15,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H3,
      name: "H3-303",
      capacity: 20,
      type: "Mentoring",
      floor: "3",
    },

    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-101",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-102",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-103",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-201",
      capacity: 5,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-202",
      capacity: 6,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-203",
      capacity: 7,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-301",
      capacity: 10,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-302",
      capacity: 15,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.H6,
      name: "H6-303",
      capacity: 20,
      type: "Mentoring",
      floor: "3",
    },

    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-101",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-102",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-103",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-201",
      capacity: 5,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-202",
      capacity: 6,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-203",
      capacity: 7,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-301",
      capacity: 10,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-302",
      capacity: 15,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.A4,
      name: "A4-303",
      capacity: 20,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-101",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-102",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-103",
      capacity: 1,
      type: "Individual",
      floor: "1",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-201",
      capacity: 5,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-202",
      capacity: 6,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-203",
      capacity: 7,
      type: "Group",
      floor: "2",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-301",
      capacity: 10,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-302",
      capacity: 15,
      type: "Mentoring",
      floor: "3",
    },
    {
      id: uuidv4(),
      ssaId: ssaId.B4,
      name: "B4-303",
      capacity: 20,
      type: "Mentoring",
      floor: "3",
    },
  ]);
}

module.exports = { seed };
