version: "1"

services:
  auth-db:
    image: mysql:5.5
    container_name: auth-db
    restart: always
    ports:
      - "3307:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - hrsApp
    env_file:
      - ./.env

  auth-service:
    build: .
    container_name: auth-service
    restart: unless-stopped
    command: npm run start
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /usr/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "8000:3000"
    env_file:
      - ./.env
    volumes:
      - /app/node_modules/
    depends_on:
      - auth-db
    networks:
      - hrsApp

volumes:
  my-db:

networks:
  hrsApp:
    name: "hrsApp"
    driver: bridge
